const fs=require('fs');let s=fs.readFileSync('LockerHero.tsx','utf8');s=s.replace('Environment,Lightformer,RoundedBox,useTexture','Environment,Lightformer,RoundedBox,useTexture,Html');s=s.replace("import './LockerHero.css';","import './LockerHero.css';\nimport {FlatFolder} from './locker/FlatFolder';\nimport {PeelSticker} from './locker/PeelSticker';");
s=s.replace('const ref=useRef<Group>(null);return <group ref={ref}',`const ref=useRef<Group>(null);const [hover,setHover]=useState(false);useFrame((state,dt)=>{if(ref.current){ref.current.rotation.z=MathUtils.damp(ref.current.rotation.z,hover?Math.sin(state.clock.elapsedTime*3)*.045:0,6,dt);ref.current.scale.setScalar(MathUtils.damp(ref.current.scale.x,hover?1.035:1,6,dt))}});return <group ref={ref}`);
s=s.replace("e.stopPropagation();document.body.style.cursor='pointer'","e.stopPropagation();setHover(true);document.body.style.cursor='pointer'").replace("onPointerOut={()=>{document.body.style.cursor='auto'}}","onPointerOut={()=>{setHover(false);document.body.style.cursor='auto'}}");
s=s.replace('function InspectBadge({active,onReturned,reduced}:{active:boolean;onReturned:()=>void;reduced:boolean})','function InspectBadge({active,onReturned,reduced,onClose}:{active:boolean;onReturned:()=>void;reduced:boolean;onClose:()=>void})');s=s.replace('new Vector3(0,1.45,2.9)','new Vector3(0,1.45,1.35)').replace('MathUtils.lerp(1,3,p)','MathUtils.lerp(1,1.75,p)').replace('<group ref={ref}><Badge/></group>','<group ref={ref}><Badge onSelect={()=>onClose()}/></group>');
const a=s.indexOf('function ProjectFolder('),b=s.indexOf('function Scene(',a);
s=s.slice(0,a)+`function ProjectFolder({id,selected,blocked,onSelect,reduced}:{id:number;selected:boolean;blocked:boolean;onSelect:()=>void;reduced:boolean}){
 const root=useRef<Group>(null),progress=useRef(0);const [expanded,setExpanded]=useState(false);
 useFrame((_,dt)=>{if(!root.current)return;progress.current=MathUtils.damp(progress.current,selected?1:0,reduced?100:5,Math.min(dt,.05));const p=progress.current,turn=MathUtils.smoothstep(p,.25,.8);root.current.position.set(MathUtils.lerp(bayCenter(1)+(id-1)*.2,0,turn),MathUtils.lerp(2.42,1.45,turn),MathUtils.lerp(-.08,1.1,MathUtils.smoothstep(p,0,.8)));root.current.rotation.y=MathUtils.lerp(-1.35,0,turn);root.current.scale.setScalar(1+turn*.65);const next=p>.85;if(next!==expanded)setExpanded(next)});
 return <group ref={root}><Html transform occlude distanceFactor={1} center><div style={{pointerEvents:blocked?'none':'auto'}}><FlatFolder name={names[id]} logo={id===1} expanded={expanded} onClick={onSelect}/></div></Html></group>
}
`+s.slice(b);
s=s.replace('onSelect,reduced}:{open:boolean','onSelect,reduced,onDoor}:{onDoor:()=>void;open:boolean');
s=s.replace('<LockerModel doorAngle=',`<group onClick={e=>{if(e.object.name==='Door_02_Body'||e.object.name==='Door_02_Inner'||e.object.parent?.name==='Door_Handle'){e.stopPropagation();onDoor()}}}><LockerModel doorAngle=`);
const start=s.indexOf('doorFaceContent={{');const end=s.indexOf('/>',start);
s=s.slice(0,start)+`doorFaceContent={Object.fromEntries([0,2,3].map(bay=>[bay,<group key={bay}>{stickerLayout.filter(t=>t.bay===bay).map(t=><group key={t.file} position={[t.x,t.y,.008]} rotation={[0,0,t.r]}><PeelSticker file={t.file} width={t.w} height={t.w*t.ratio}/></group>)}{bay===3&&<group position={[.08,.28,.012]} rotation={[0,0,-.09]}><Picture file="photo.png" width={.4} height={.5}/></group>}</group>]))}/></group>`+s.slice(s.indexOf('\n <mesh position={[-.9',start));
s=s.replace('onSelect={()=>onSelect(id)}','onSelect={()=>onSelect(selection===id?null:id)}');
s=s.replace("reduced={reduced} onReturned", "reduced={reduced} onClose={()=>onSelect(null)} onReturned");
s=s.replace('const closeRef=useRef<HTMLButtonElement>(null);const previousFocus=useRef<HTMLElement|null>(null);','const doorTimer=useRef<ReturnType<typeof setTimeout>|null>(null);\n const toggleDoor=()=>{setSelection(null);if(doorTimer.current)clearTimeout(doorTimer.current);doorTimer.current=setTimeout(()=>setOpen(v=>!v),selection!==null||badgeVisible?1300:0)};');
const e0=s.indexOf(' useEffect(()=>{if(selection===null)return;'),e1=s.indexOf(' return <div className="locker-stage">',e0);s=s.slice(0,e0)+` useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelection(null)};window.addEventListener('keydown',handler);return()=>{window.removeEventListener('keydown',handler);if(doorTimer.current)clearTimeout(doorTimer.current)}},[]);\n`+s.slice(e1);
s=s.replace('onSelect={setSelection} reduced={reduced}','onSelect={setSelection} reduced={reduced} onDoor={toggleDoor}');
s=s.replace('<button ref={closeRef} onClick={()=>setSelection(null)} aria-label="关闭检视">收回 ×</button>','');s=s.replace('移动鼠标查看 · Esc 收回','再次点击物件收回 · Esc 也可收回');
s=s.replace('<div className="locker-controls" inert={selection!==null}><button onClick={()=>setOpen(v=>!v)} disabled={badgeVisible}>','<div className="locker-controls"><button onClick={toggleDoor}>');s=s.replace('onClick={()=>setSelection(id)}','onClick={()=>setSelection(selection===id?null:id)}');
const layout=[['sticker-one.png',0,.17,.36,.23,.85,-.17],['sticker-two.png',0,-.12,-.42,.22,1,.17],['sticker-3.png',0,-.17,.65,.22,1,-.12],['sticker-4.png',0,.15,-.7,.19,1,.22],['sticker-5.png',2,.12,.6,.23,1,.15],['sticker-6.png',2,-.12,.16,.21,1,-.16],['sticker-7.png',2,.17,-.45,.25,1,.12],['sticker-8.png',0,.04,-.03,.19,1,.09],['sticker-9.png',3,-.1,-.35,.22,1,-.18],['sticker-10.png',2,-.08,-.78,.24,1,.14],['sticker-11.png',3,.18,-.7,.2,1,-.08]];
s=s.replace('const badgeOrigin=', 'const stickerLayout='+JSON.stringify(layout.map(([file,bay,x,y,w,ratio,r])=>({file,bay,x,y,w,ratio,r})))+';\nconst badgeOrigin=');
fs.writeFileSync('LockerHero.tsx',s);
